In [13]:
import numpy as np



In [14]:
# Define the dataset of house prices and features
X = np.array([[2600], [3000], [3200], [3600], [4000]])
y = np.array([[550000], [565000], [610000], [680000], [725000]])



In [15]:
X

array([[2600],
       [3000],
       [3200],
       [3600],
       [4000]])

In [16]:
np.ones_like(X)

array([[1],
       [1],
       [1],
       [1],
       [1]])

In [17]:
# Add a column of ones to the input matrix to represent the intercept term
X = np.hstack((np.ones_like(X), X))



In [18]:
X

array([[   1, 2600],
       [   1, 3000],
       [   1, 3200],
       [   1, 3600],
       [   1, 4000]])

In [19]:
# Compute the coefficients of the linear regression using the Least Squares method
coefficients = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)


In [20]:

# Print the coefficients: intercept and slope
print("Intercept:", coefficients[0])
print("Slope:", coefficients[1])



Intercept: [180616.43835617]
Slope: [135.78767123]


In [21]:
# Usee the linear regression model to predict the price of a new house
new_house_size = 3500
predicted_price = coefficients[0] + coefficients[1] * new_house_size
print("Predicted price for a house of size", new_house_size, "sq.ft.:", predicted_price)

Predicted price for a house of size 3500 sq.ft.: [655873.28767123]
